In [1]:
from catboost import CatBoostClassifier, Pool  
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import VotingClassifier
import pandas as pd
import numpy as np

In [25]:
df=pd.read_csv('train_x.csv') #인덱스 col=0도 check!
df_test=pd.read_csv('test_c.csv')
sub=pd.read_csv('sample_submission.csv') 

In [26]:
train_y = df['voted']
df.drop(['voted'], axis=1,inplace=True)

In [27]:
gbc = GradientBoostingClassifier()
cat = CatBoostClassifier()
gbm = LGBMClassifier()

In [17]:
voting = VotingClassifier(
            estimators=[('cat', cat), ('gbc', gbc), ('gbm', gbm)],
            voting='soft')
voting.fit(df, train_y)
v_pred=voting.predict(df_test)

Learning rate set to 0.051607
0:	learn: 0.6760060	total: 44.4ms	remaining: 44.4s
1:	learn: 0.6616175	total: 53.3ms	remaining: 26.6s
2:	learn: 0.6519829	total: 90.1ms	remaining: 29.9s
3:	learn: 0.6408980	total: 107ms	remaining: 26.7s
4:	learn: 0.6314205	total: 117ms	remaining: 23.3s
5:	learn: 0.6251277	total: 129ms	remaining: 21.4s
6:	learn: 0.6175090	total: 138ms	remaining: 19.5s
7:	learn: 0.6126327	total: 146ms	remaining: 18.1s
8:	learn: 0.6065772	total: 153ms	remaining: 16.8s
9:	learn: 0.6028897	total: 162ms	remaining: 16s
10:	learn: 0.5992932	total: 172ms	remaining: 15.5s
11:	learn: 0.5961163	total: 182ms	remaining: 15s
12:	learn: 0.5936158	total: 199ms	remaining: 15.1s
13:	learn: 0.5899215	total: 234ms	remaining: 16.5s
14:	learn: 0.5876679	total: 246ms	remaining: 16.2s
15:	learn: 0.5857788	total: 256ms	remaining: 15.7s
16:	learn: 0.5837607	total: 266ms	remaining: 15.4s
17:	learn: 0.5821150	total: 278ms	remaining: 15.2s
18:	learn: 0.5805697	total: 286ms	remaining: 14.8s
19:	learn: 0

164:	learn: 0.5473831	total: 4.58s	remaining: 23.2s
165:	learn: 0.5472657	total: 4.59s	remaining: 23.1s
166:	learn: 0.5471752	total: 4.65s	remaining: 23.2s
167:	learn: 0.5470965	total: 4.66s	remaining: 23.1s
168:	learn: 0.5469995	total: 4.67s	remaining: 23s
169:	learn: 0.5469197	total: 4.69s	remaining: 22.9s
170:	learn: 0.5468852	total: 4.72s	remaining: 22.9s
171:	learn: 0.5467920	total: 4.73s	remaining: 22.8s
172:	learn: 0.5467238	total: 4.74s	remaining: 22.6s
173:	learn: 0.5466505	total: 4.74s	remaining: 22.5s
174:	learn: 0.5465700	total: 4.75s	remaining: 22.4s
175:	learn: 0.5465088	total: 4.76s	remaining: 22.3s
176:	learn: 0.5464414	total: 4.78s	remaining: 22.2s
177:	learn: 0.5463964	total: 4.79s	remaining: 22.1s
178:	learn: 0.5463019	total: 4.8s	remaining: 22s
179:	learn: 0.5462180	total: 4.83s	remaining: 22s
180:	learn: 0.5461541	total: 4.84s	remaining: 21.9s
181:	learn: 0.5461080	total: 4.88s	remaining: 22s
182:	learn: 0.5460655	total: 4.89s	remaining: 21.9s
183:	learn: 0.5460125

331:	learn: 0.5364445	total: 8.78s	remaining: 17.7s
332:	learn: 0.5363905	total: 8.8s	remaining: 17.6s
333:	learn: 0.5363262	total: 8.87s	remaining: 17.7s
334:	learn: 0.5362606	total: 8.88s	remaining: 17.6s
335:	learn: 0.5361780	total: 8.9s	remaining: 17.6s
336:	learn: 0.5361445	total: 8.91s	remaining: 17.5s
337:	learn: 0.5360948	total: 8.95s	remaining: 17.5s
338:	learn: 0.5360053	total: 8.96s	remaining: 17.5s
339:	learn: 0.5359233	total: 8.97s	remaining: 17.4s
340:	learn: 0.5358471	total: 9.01s	remaining: 17.4s
341:	learn: 0.5357915	total: 9.03s	remaining: 17.4s
342:	learn: 0.5357157	total: 9.05s	remaining: 17.3s
343:	learn: 0.5356358	total: 9.08s	remaining: 17.3s
344:	learn: 0.5355721	total: 9.1s	remaining: 17.3s
345:	learn: 0.5354929	total: 9.15s	remaining: 17.3s
346:	learn: 0.5354127	total: 9.16s	remaining: 17.2s
347:	learn: 0.5353661	total: 9.18s	remaining: 17.2s
348:	learn: 0.5353173	total: 9.19s	remaining: 17.1s
349:	learn: 0.5352898	total: 9.25s	remaining: 17.2s
350:	learn: 0.5

492:	learn: 0.5277989	total: 13s	remaining: 13.4s
493:	learn: 0.5277406	total: 13.1s	remaining: 13.4s
494:	learn: 0.5277196	total: 13.1s	remaining: 13.4s
495:	learn: 0.5276817	total: 13.1s	remaining: 13.3s
496:	learn: 0.5276081	total: 13.1s	remaining: 13.3s
497:	learn: 0.5275775	total: 13.2s	remaining: 13.3s
498:	learn: 0.5275267	total: 13.2s	remaining: 13.3s
499:	learn: 0.5274856	total: 13.2s	remaining: 13.2s
500:	learn: 0.5274380	total: 13.3s	remaining: 13.2s
501:	learn: 0.5273923	total: 13.3s	remaining: 13.2s
502:	learn: 0.5273373	total: 13.3s	remaining: 13.2s
503:	learn: 0.5272974	total: 13.4s	remaining: 13.2s
504:	learn: 0.5272544	total: 13.4s	remaining: 13.1s
505:	learn: 0.5272294	total: 13.4s	remaining: 13.1s
506:	learn: 0.5271516	total: 13.5s	remaining: 13.1s
507:	learn: 0.5271164	total: 13.5s	remaining: 13.1s
508:	learn: 0.5270879	total: 13.5s	remaining: 13s
509:	learn: 0.5270489	total: 13.5s	remaining: 13s
510:	learn: 0.5269940	total: 13.5s	remaining: 12.9s
511:	learn: 0.5269

657:	learn: 0.5203563	total: 17.2s	remaining: 8.94s
658:	learn: 0.5202876	total: 17.2s	remaining: 8.91s
659:	learn: 0.5202589	total: 17.2s	remaining: 8.88s
660:	learn: 0.5202097	total: 17.3s	remaining: 8.88s
661:	learn: 0.5201645	total: 17.3s	remaining: 8.85s
662:	learn: 0.5201140	total: 17.4s	remaining: 8.84s
663:	learn: 0.5200785	total: 17.4s	remaining: 8.81s
664:	learn: 0.5200476	total: 17.4s	remaining: 8.78s
665:	learn: 0.5199891	total: 17.5s	remaining: 8.77s
666:	learn: 0.5199475	total: 17.5s	remaining: 8.73s
667:	learn: 0.5199011	total: 17.5s	remaining: 8.71s
668:	learn: 0.5198311	total: 17.6s	remaining: 8.69s
669:	learn: 0.5197841	total: 17.6s	remaining: 8.66s
670:	learn: 0.5197477	total: 17.6s	remaining: 8.65s
671:	learn: 0.5196927	total: 17.7s	remaining: 8.62s
672:	learn: 0.5196652	total: 17.7s	remaining: 8.62s
673:	learn: 0.5196432	total: 17.8s	remaining: 8.59s
674:	learn: 0.5195946	total: 17.8s	remaining: 8.58s
675:	learn: 0.5195727	total: 17.8s	remaining: 8.55s
676:	learn: 

822:	learn: 0.5137094	total: 21.3s	remaining: 4.59s
823:	learn: 0.5136796	total: 21.3s	remaining: 4.56s
824:	learn: 0.5136581	total: 21.3s	remaining: 4.53s
825:	learn: 0.5136125	total: 21.4s	remaining: 4.5s
826:	learn: 0.5135776	total: 21.4s	remaining: 4.47s
827:	learn: 0.5135562	total: 21.4s	remaining: 4.44s
828:	learn: 0.5134950	total: 21.4s	remaining: 4.41s
829:	learn: 0.5134496	total: 21.4s	remaining: 4.38s
830:	learn: 0.5134129	total: 21.4s	remaining: 4.36s
831:	learn: 0.5133778	total: 21.4s	remaining: 4.33s
832:	learn: 0.5133375	total: 21.4s	remaining: 4.3s
833:	learn: 0.5132977	total: 21.5s	remaining: 4.27s
834:	learn: 0.5132527	total: 21.5s	remaining: 4.24s
835:	learn: 0.5131976	total: 21.5s	remaining: 4.21s
836:	learn: 0.5131793	total: 21.5s	remaining: 4.18s
837:	learn: 0.5131599	total: 21.5s	remaining: 4.15s
838:	learn: 0.5131264	total: 21.5s	remaining: 4.12s
839:	learn: 0.5131042	total: 21.5s	remaining: 4.09s
840:	learn: 0.5130738	total: 21.5s	remaining: 4.07s
841:	learn: 0.

985:	learn: 0.5081538	total: 23s	remaining: 326ms
986:	learn: 0.5081300	total: 23s	remaining: 303ms
987:	learn: 0.5080773	total: 23s	remaining: 279ms
988:	learn: 0.5080496	total: 23s	remaining: 256ms
989:	learn: 0.5080138	total: 23s	remaining: 233ms
990:	learn: 0.5079916	total: 23s	remaining: 209ms
991:	learn: 0.5079803	total: 23s	remaining: 186ms
992:	learn: 0.5079173	total: 23.1s	remaining: 163ms
993:	learn: 0.5078750	total: 23.1s	remaining: 139ms
994:	learn: 0.5078256	total: 23.1s	remaining: 116ms
995:	learn: 0.5077693	total: 23.1s	remaining: 92.8ms
996:	learn: 0.5077369	total: 23.1s	remaining: 69.6ms
997:	learn: 0.5076822	total: 23.1s	remaining: 46.3ms
998:	learn: 0.5076511	total: 23.1s	remaining: 23.2ms
999:	learn: 0.5075863	total: 23.1s	remaining: 0us


In [39]:
suv=pd.DataFrame(v_pred, columns = ['voted'])

In [40]:
sub['voted'] = suv['voted']

In [41]:
sub.to_csv("subvoting.csv", index=False)

In [19]:
gbc.fit(df, train_y)

GradientBoostingClassifier()

In [20]:
gbc_pre=gbc.predict(df_test)
gbc_pre

array([2, 2, 1, ..., 1, 1, 2], dtype=int64)

In [28]:
gbcsuv=pd.DataFrame(gbc_pre, columns = ['voted'])

In [29]:
sub['voted'] = gbcsuv['voted']

In [30]:
sub.to_csv("gbc제출.csv", index=False)

In [31]:
cat.fit(df, train_y)

Learning rate set to 0.051607
0:	learn: 0.6760060	total: 27ms	remaining: 27s
1:	learn: 0.6616175	total: 40ms	remaining: 19.9s
2:	learn: 0.6519829	total: 51.4ms	remaining: 17.1s
3:	learn: 0.6408980	total: 90.4ms	remaining: 22.5s
4:	learn: 0.6314205	total: 103ms	remaining: 20.4s
5:	learn: 0.6251277	total: 114ms	remaining: 18.9s
6:	learn: 0.6175090	total: 128ms	remaining: 18.2s
7:	learn: 0.6126327	total: 141ms	remaining: 17.5s
8:	learn: 0.6065772	total: 151ms	remaining: 16.6s
9:	learn: 0.6028897	total: 160ms	remaining: 15.8s
10:	learn: 0.5992932	total: 170ms	remaining: 15.3s
11:	learn: 0.5961163	total: 181ms	remaining: 14.9s
12:	learn: 0.5936158	total: 199ms	remaining: 15.1s
13:	learn: 0.5899215	total: 232ms	remaining: 16.3s
14:	learn: 0.5876679	total: 254ms	remaining: 16.6s
15:	learn: 0.5857788	total: 267ms	remaining: 16.4s
16:	learn: 0.5837607	total: 292ms	remaining: 16.9s
17:	learn: 0.5821150	total: 323ms	remaining: 17.6s
18:	learn: 0.5805697	total: 339ms	remaining: 17.5s
19:	learn: 0.

169:	learn: 0.5469197	total: 3.35s	remaining: 16.4s
170:	learn: 0.5468852	total: 3.36s	remaining: 16.3s
171:	learn: 0.5467920	total: 3.37s	remaining: 16.2s
172:	learn: 0.5467238	total: 3.38s	remaining: 16.2s
173:	learn: 0.5466505	total: 3.39s	remaining: 16.1s
174:	learn: 0.5465700	total: 3.42s	remaining: 16.1s
175:	learn: 0.5465088	total: 3.43s	remaining: 16.1s
176:	learn: 0.5464414	total: 3.44s	remaining: 16s
177:	learn: 0.5463964	total: 3.45s	remaining: 15.9s
178:	learn: 0.5463019	total: 3.46s	remaining: 15.9s
179:	learn: 0.5462180	total: 3.47s	remaining: 15.8s
180:	learn: 0.5461541	total: 3.48s	remaining: 15.7s
181:	learn: 0.5461080	total: 3.48s	remaining: 15.7s
182:	learn: 0.5460655	total: 3.49s	remaining: 15.6s
183:	learn: 0.5460125	total: 3.5s	remaining: 15.5s
184:	learn: 0.5459440	total: 3.51s	remaining: 15.4s
185:	learn: 0.5458784	total: 3.51s	remaining: 15.4s
186:	learn: 0.5458283	total: 3.52s	remaining: 15.3s
187:	learn: 0.5457692	total: 3.53s	remaining: 15.2s
188:	learn: 0.5

329:	learn: 0.5365922	total: 5.08s	remaining: 10.3s
330:	learn: 0.5365267	total: 5.09s	remaining: 10.3s
331:	learn: 0.5364445	total: 5.1s	remaining: 10.3s
332:	learn: 0.5363905	total: 5.1s	remaining: 10.2s
333:	learn: 0.5363262	total: 5.12s	remaining: 10.2s
334:	learn: 0.5362606	total: 5.14s	remaining: 10.2s
335:	learn: 0.5361780	total: 5.15s	remaining: 10.2s
336:	learn: 0.5361445	total: 5.16s	remaining: 10.2s
337:	learn: 0.5360948	total: 5.17s	remaining: 10.1s
338:	learn: 0.5360053	total: 5.18s	remaining: 10.1s
339:	learn: 0.5359233	total: 5.19s	remaining: 10.1s
340:	learn: 0.5358471	total: 5.2s	remaining: 10.1s
341:	learn: 0.5357915	total: 5.21s	remaining: 10s
342:	learn: 0.5357157	total: 5.22s	remaining: 9.99s
343:	learn: 0.5356358	total: 5.23s	remaining: 9.97s
344:	learn: 0.5355721	total: 5.24s	remaining: 9.94s
345:	learn: 0.5354929	total: 5.25s	remaining: 9.92s
346:	learn: 0.5354127	total: 5.26s	remaining: 9.9s
347:	learn: 0.5353661	total: 5.29s	remaining: 9.91s
348:	learn: 0.5353

493:	learn: 0.5277406	total: 6.79s	remaining: 6.95s
494:	learn: 0.5277196	total: 6.8s	remaining: 6.93s
495:	learn: 0.5276817	total: 6.81s	remaining: 6.92s
496:	learn: 0.5276081	total: 6.82s	remaining: 6.9s
497:	learn: 0.5275775	total: 6.85s	remaining: 6.9s
498:	learn: 0.5275267	total: 6.86s	remaining: 6.89s
499:	learn: 0.5274856	total: 6.88s	remaining: 6.88s
500:	learn: 0.5274380	total: 6.91s	remaining: 6.89s
501:	learn: 0.5273923	total: 6.92s	remaining: 6.87s
502:	learn: 0.5273373	total: 6.93s	remaining: 6.85s
503:	learn: 0.5272974	total: 6.95s	remaining: 6.83s
504:	learn: 0.5272544	total: 6.95s	remaining: 6.82s
505:	learn: 0.5272294	total: 6.96s	remaining: 6.8s
506:	learn: 0.5271516	total: 6.97s	remaining: 6.78s
507:	learn: 0.5271164	total: 6.98s	remaining: 6.76s
508:	learn: 0.5270879	total: 6.99s	remaining: 6.74s
509:	learn: 0.5270489	total: 7s	remaining: 6.72s
510:	learn: 0.5269940	total: 7.03s	remaining: 6.72s
511:	learn: 0.5269336	total: 7.04s	remaining: 6.71s
512:	learn: 0.52686

652:	learn: 0.5205766	total: 9.99s	remaining: 5.31s
653:	learn: 0.5205196	total: 10s	remaining: 5.3s
654:	learn: 0.5204667	total: 10s	remaining: 5.29s
655:	learn: 0.5204213	total: 10.1s	remaining: 5.27s
656:	learn: 0.5203702	total: 10.1s	remaining: 5.26s
657:	learn: 0.5203563	total: 10.1s	remaining: 5.24s
658:	learn: 0.5202876	total: 10.1s	remaining: 5.23s
659:	learn: 0.5202589	total: 10.1s	remaining: 5.21s
660:	learn: 0.5202097	total: 10.1s	remaining: 5.2s
661:	learn: 0.5201645	total: 10.1s	remaining: 5.18s
662:	learn: 0.5201140	total: 10.2s	remaining: 5.17s
663:	learn: 0.5200785	total: 10.2s	remaining: 5.16s
664:	learn: 0.5200476	total: 10.2s	remaining: 5.15s
665:	learn: 0.5199891	total: 10.2s	remaining: 5.13s
666:	learn: 0.5199475	total: 10.3s	remaining: 5.12s
667:	learn: 0.5199011	total: 10.3s	remaining: 5.1s
668:	learn: 0.5198311	total: 10.3s	remaining: 5.08s
669:	learn: 0.5197841	total: 10.3s	remaining: 5.07s
670:	learn: 0.5197477	total: 10.3s	remaining: 5.06s
671:	learn: 0.51969

820:	learn: 0.5138139	total: 12.8s	remaining: 2.79s
821:	learn: 0.5137817	total: 12.8s	remaining: 2.78s
822:	learn: 0.5137094	total: 12.8s	remaining: 2.76s
823:	learn: 0.5136796	total: 12.9s	remaining: 2.75s
824:	learn: 0.5136581	total: 12.9s	remaining: 2.73s
825:	learn: 0.5136125	total: 12.9s	remaining: 2.72s
826:	learn: 0.5135776	total: 12.9s	remaining: 2.7s
827:	learn: 0.5135562	total: 12.9s	remaining: 2.69s
828:	learn: 0.5134950	total: 12.9s	remaining: 2.67s
829:	learn: 0.5134496	total: 13s	remaining: 2.65s
830:	learn: 0.5134129	total: 13s	remaining: 2.64s
831:	learn: 0.5133778	total: 13s	remaining: 2.62s
832:	learn: 0.5133375	total: 13s	remaining: 2.61s
833:	learn: 0.5132977	total: 13s	remaining: 2.6s
834:	learn: 0.5132527	total: 13.1s	remaining: 2.58s
835:	learn: 0.5131976	total: 13.1s	remaining: 2.56s
836:	learn: 0.5131793	total: 13.1s	remaining: 2.55s
837:	learn: 0.5131599	total: 13.1s	remaining: 2.53s
838:	learn: 0.5131264	total: 13.1s	remaining: 2.51s
839:	learn: 0.5131042	to

993:	learn: 0.5078750	total: 15.2s	remaining: 91.5ms
994:	learn: 0.5078256	total: 15.2s	remaining: 76.2ms
995:	learn: 0.5077693	total: 15.2s	remaining: 60.9ms
996:	learn: 0.5077369	total: 15.2s	remaining: 45.7ms
997:	learn: 0.5076822	total: 15.2s	remaining: 30.4ms
998:	learn: 0.5076511	total: 15.2s	remaining: 15.2ms
999:	learn: 0.5075863	total: 15.2s	remaining: 0us


In [32]:
cat_pre=cat.predict(df_test)
cat_pre

array([2, 2, 1, ..., 1, 1, 2], dtype=int64)

In [33]:
catsuv=pd.DataFrame(cat_pre, columns = ['voted'])

In [34]:
sub['voted'] = catsuv['voted']

In [35]:
sub.to_csv("cat제출.csv", index=False)

In [36]:
gbm.fit(df, train_y)

LGBMClassifier()

In [37]:
gbm_pre=gbm.predict(df_test)
gbm_pre

array([2, 2, 1, ..., 1, 1, 2], dtype=int64)